# Generated by Django 5.2.8 on 2025-12-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_banner_banneroffer_carouselslide_minicategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniproduct',
            old_name='name',
            new_name='miniProductname',
        ),
    ]
