# Generated by Django 6.0 on 2025-12-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_billingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproduct',
            name='categoryID',
        ),
        migrations.DeleteModel(
            name='MiniCategory',
        ),
        migrations.DeleteModel(
            name='MiniProduct',
        ),
    ]
