# Generated by Django 6.0 on 2025-12-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_miniproduct_categoryid_delete_minicategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bestseller',
        ),
    ]
