# Generated by Django 6.0 on 2025-12-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
